// Generated by build.py. Edit the SLIDES spec there, not this file.
window.KIOSK_SLIDES = [
  {
    "id": "thermal",
    "label": "Thermal",
    "key": "T",
    "layout": "wide",
    "title": "Thermal assist",
    "lines": [],
    "dur": 18,
    "qr": null,
    "cornerQr": true,
    "card": "header",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/thermal-deadband.mp4",
      "poster": "img/poster-thermal-deadband.jpg",
      "dur": 18.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "wind",
    "label": "Wind",
    "key": "W",
    "layout": "wide",
    "title": "Wind estimation",
    "lines": [],
    "dur": 18,
    "qr": null,
    "cornerQr": true,
    "card": "header",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/wind-visible.mp4",
      "poster": "img/poster-wind-visible.jpg",
      "dur": 18.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "nav",
    "label": "Nav",
    "key": "N",
    "layout": "wide",
    "title": "Competition navigation",
    "lines": [],
    "dur": 15.8,
    "qr": null,
    "cornerQr": true,
    "card": "header",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/navigation-real.mp4",
      "poster": "img/poster-navigation-real.jpg",
      "dur": 15.8,
      "w": 1600,
      "h": 900
    }
  },
  {
    "id": "sideview",
    "label": "Glide",
    "key": "S",
    "layout": "wide",
    "title": "Side view and glide range",
    "lines": [],
    "dur": 16.1,
    "qr": null,
    "cornerQr": true,
    "card": "header",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/sideview-fixed.mp4",
      "poster": "img/poster-sideview-fixed.jpg",
      "dur": 16.1,
      "w": 1600,
      "h": 900
    }
  },
  {
    "id": "replay",
    "label": "3D",
    "key": "3",
    "layout": "wide",
    "title": "3D replay",
    "lines": [],
    "dur": 18,
    "qr": null,
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/glacier-replay.mp4",
      "poster": "img/poster-glacier-replay.jpg",
      "dur": 18.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "tracking",
    "label": "Track",
    "key": "L",
    "layout": "phone",
    "title": "Live tracking",
    "lines": [
      "Every second online. Direct radio off-grid."
    ],
    "dur": 14,
    "qr": null,
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/klipp-tracking.mp4",
      "poster": "img/poster-klipp-tracking.jpg",
      "dur": 5.12,
      "w": 780,
      "h": 1688
    }
  },
  {
    "id": "comms",
    "label": "Voice",
    "key": "C",
    "layout": "wide",
    "title": "Group voice",
    "lines": [],
    "dur": 9,
    "qr": null,
    "cornerQr": true,
    "card": "top",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/voice-simple.mp4",
      "poster": "img/poster-voice-simple.jpg",
      "dur": 9.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "vhf",
    "label": "VHF",
    "key": "R",
    "layout": "wide",
    "title": "VHF bridge",
    "lines": [],
    "dur": 9,
    "qr": null,
    "cornerQr": true,
    "card": "top",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/vhf-simple.mp4",
      "poster": "img/poster-vhf-simple.jpg",
      "dur": 9.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "hardware",
    "label": "Button",
    "key": "H",
    "layout": "phone",
    "title": "Button on the brake line",
    "lines": [
      "Customizable controls."
    ],
    "dur": 14,
    "qr": null,
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/klipp-knapp.mp4",
      "poster": "img/poster-klipp-knapp.jpg",
      "dur": 8.85,
      "w": 1080,
      "h": 1714
    }
  },
  {
    "id": "forecast",
    "label": "Weather",
    "key": "F",
    "layout": "wide",
    "title": "Weather forecast",
    "lines": [],
    "dur": 20,
    "qr": null,
    "cornerQr": true,
    "card": "header",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/weather-comparison.mp4",
      "poster": "img/poster-weather-comparison.jpg",
      "dur": 20.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "regional",
    "label": "Regional",
    "key": null,
    "layout": "seq",
    "title": "Regional forecast",
    "lines": [
      "Coming soon."
    ],
    "dur": 14,
    "qr": null,
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [
      "in",
      "in"
    ],
    "kbOriginSeq": [
      "46% 64%",
      "39% 50%"
    ],
    "images": [
      {
        "type": "image",
        "src": "img/algo-regions-europe.png",
        "poster": "img/algo-regions-europe.png",
        "w": 1920,
        "h": 1080
      },
      {
        "type": "image",
        "src": "img/algo-regions-alps.png",
        "poster": "img/algo-regions-alps.png",
        "w": 1920,
        "h": 1080
      }
    ]
  },
  {
    "id": "contacts",
    "label": "Contacts",
    "key": "G",
    "layout": "wide",
    "title": "Ground contacts",
    "lines": [
      "Your ground contacts stay informed."
    ],
    "dur": 17.2,
    "qr": null,
    "cornerQr": false,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/contacts-simple.mp4",
      "poster": "img/poster-contacts-simple.jpg",
      "dur": 17.2,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "flights",
    "label": "Analyse",
    "key": "X",
    "layout": "wide",
    "title": "Analyse your flight",
    "lines": [
      "Glides and thermals, your turn direction, the air you flew in."
    ],
    "dur": 24,
    "qr": null,
    "cornerQr": true,
    "card": "header",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/analyse-large.mp4",
      "poster": "img/poster-analyse-large.jpg",
      "dur": 24.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "segments",
    "label": "Activities",
    "key": "I",
    "layout": "phone",
    "title": "Automatic activity segments",
    "lines": [],
    "dur": 17.4,
    "qr": null,
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/activity-segments.mp4",
      "poster": "img/poster-activity-segments.jpg",
      "dur": 17.4,
      "w": 1080,
      "h": 1280
    }
  },
  {
    "id": "areacontest",
    "label": "Area",
    "key": "A",
    "layout": "phone",
    "title": "AreaContest",
    "lines": [],
    "dur": 20,
    "qr": "coupe",
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/coupe_whale_v8.mp4",
      "poster": "img/poster-coupe_whale_v8.jpg",
      "dur": 23.4,
      "w": 1080,
      "h": 1920
    }
  },
  {
    "id": "offline",
    "label": "Offline",
    "key": "O",
    "layout": "phone",
    "title": "Works without coverage",
    "lines": [],
    "dur": 14,
    "qr": null,
    "cornerQr": true,
    "card": "bottom",
    "scrim": false,
    "kb": "in",
    "kbSeq": [],
    "kbOriginSeq": [],
    "media": {
      "type": "video",
      "src": "video/klipp-backcountry.mp4",
      "poster": "img/poster-klipp-backcountry.jpg",
      "dur": 12.01,
      "w": 608,
      "h": 1080
    }
  }
];
