// Generated by build.py. Edit the SLIDES spec there, not this file.
window.KIOSK_SLIDES = [
  {
    "id": "home",
    "label": "Home",
    "key": "Home",
    "layout": "title",
    "title": "All you need in one flight app",
    "lines": [
      "pgpilot.app, free, iOS and Android"
    ],
    "dur": 15,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/bir-3d.mp4",
      "poster": "img/poster-bir-3d.jpg",
      "dur": 38.1,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "thermal",
    "label": "Thermal",
    "key": "T",
    "layout": "wide",
    "title": "Thermal assist",
    "lines": [
      "The bubble is drawn where the lift was.",
      "The vario tells you how strong."
    ],
    "dur": 20,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/thermal-assist.mp4",
      "poster": "img/poster-thermal-assist.jpg",
      "dur": 22.03,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "wind",
    "label": "Wind",
    "key": "W",
    "layout": "wide",
    "title": "Wind estimation",
    "lines": [
      "Learned from your own circles, no sensor needed.",
      "Updated every turn."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/wind-estimation.mp4",
      "poster": "img/poster-wind-estimation.jpg",
      "dur": 22.03,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "nav",
    "label": "Nav",
    "key": "N",
    "layout": "wide",
    "title": "Navigation",
    "lines": [
      "Tasks, waypoints and a heading line.",
      "Glide to goal on the map."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/navigation.mp4",
      "poster": "img/poster-navigation.jpg",
      "dur": 20.03,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "sideview",
    "label": "Side view",
    "key": "S",
    "layout": "wide",
    "title": "Side view and glide range",
    "lines": [
      "Will you clear that ridge?",
      "Glide rays and range contours say so before you commit."
    ],
    "dur": 20,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/sideview-glide.mp4",
      "poster": "img/poster-sideview-glide.jpg",
      "dur": 22.03,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "replay",
    "label": "3D",
    "key": "3",
    "layout": "wide",
    "title": "3D replay",
    "lines": [
      "Fly it again in 3D.",
      "Every flight, every thermal, every glide."
    ],
    "dur": 22,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/replay-3d.mp4",
      "poster": "img/poster-replay-3d.jpg",
      "dur": 21.0,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "tracking",
    "label": "Tracking",
    "key": "L",
    "layout": "phone",
    "title": "Live tracking",
    "lines": [
      "See your friends in the air. One position per second.",
      "OGN, FLARM and inReach on the same map."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/klipp-tracking.mp4",
      "poster": "img/poster-klipp-tracking.jpg",
      "dur": 5.12,
      "w": 780,
      "h": 1688
    }
  },
  {
    "id": "comms",
    "label": "Comms",
    "key": "C",
    "layout": "phone",
    "title": "Group voice and chat",
    "lines": [
      "Push to talk to the whole group over the internet.",
      "VHF bridged into the same channel."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "image",
      "src": "img/app-comms.png",
      "poster": "img/app-comms.png",
      "w": 855,
      "h": 1920
    }
  },
  {
    "id": "hardware",
    "label": "Hardware",
    "key": "H",
    "layout": "phone",
    "title": "Button on the brake line",
    "lines": [
      "Hold to talk.",
      "Double tap to zoom in, triple tap to zoom out.",
      "Tap and hold for the voice assistant."
    ],
    "dur": 20,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/klipp-knapp.mp4",
      "poster": "img/poster-klipp-knapp.jpg",
      "dur": 8.85,
      "w": 1080,
      "h": 1714
    }
  },
  {
    "id": "forecast",
    "label": "Forecast",
    "key": "F",
    "layout": "wide",
    "title": "Wind and forecast at the takeoff",
    "lines": [
      "Wind stations with history, airgram forecast for the launch.",
      "Before you leave home."
    ],
    "dur": 20,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/forecast-airgram.mp4",
      "poster": "img/poster-forecast-airgram.jpg",
      "dur": 20.73,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "contacts",
    "label": "Contacts",
    "key": "G",
    "layout": "phone",
    "title": "Ground contacts",
    "lines": [
      "Your people get a message when you take off and when you land.",
      "SMS, email or push."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/klipp-start.mp4",
      "poster": "img/poster-klipp-start.jpg",
      "dur": 12.0,
      "w": 780,
      "h": 1688
    }
  },
  {
    "id": "flights",
    "label": "Flights",
    "key": "X",
    "layout": "wide",
    "title": "Your flights, synced",
    "lines": [
      "XContest and Flightlog sync, IGC export,",
      "segments split automatically."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": true,
    "media": {
      "type": "image",
      "src": "img/app-flightdetails.jpg",
      "poster": "img/app-flightdetails.jpg",
      "w": 1440,
      "h": 810
    }
  },
  {
    "id": "areacontest",
    "label": "AreaContest",
    "key": "A",
    "layout": "phone",
    "title": "AreaContest",
    "lines": [
      "Fly around an area to claim it.",
      "Whoever has the biggest claim rules it."
    ],
    "dur": 25,
    "qr": "coupe",
    "footnote": "This week: the whale over Saint-Hilaire. Biggest claim on Sunday 13:00 wins.",
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/coupe_whale_v8.mp4",
      "poster": "img/poster-coupe_whale_v8.jpg",
      "dur": 23.4,
      "w": 1080,
      "h": 1920
    },
    "bg": {
      "type": "video",
      "src": "video/areacontest-whale.mp4",
      "poster": "img/poster-areacontest-whale.jpg",
      "dur": 20.73,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "board",
    "label": "Board",
    "key": null,
    "layout": "wide",
    "title": "The whale, right now",
    "lines": [
      "The real board, scored every hour this week. Everyone on pgpilot is already in."
    ],
    "dur": 21,
    "qr": "coupe",
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/areacontest-whale.mp4",
      "poster": "img/poster-areacontest-whale.jpg",
      "dur": 20.73,
      "w": 1920,
      "h": 1080
    }
  },
  {
    "id": "offline",
    "label": "Offline",
    "key": "O",
    "layout": "phone",
    "title": "Works without coverage",
    "lines": [
      "Maps, terrain and instruments offline.",
      "Backcountry ready."
    ],
    "dur": 18,
    "qr": null,
    "footnote": null,
    "cornerQr": true,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/klipp-backcountry.mp4",
      "poster": "img/poster-klipp-backcountry.jpg",
      "dur": 12.01,
      "w": 608,
      "h": 1080
    }
  },
  {
    "id": "try",
    "label": "Try it",
    "key": null,
    "layout": "closing",
    "title": "Try it now",
    "lines": [
      "Ask us at the stand"
    ],
    "dur": 20,
    "qr": "pgpilot",
    "footnote": null,
    "cornerQr": false,
    "dim": false,
    "media": {
      "type": "video",
      "src": "video/bir-3d.mp4",
      "poster": "img/poster-bir-3d.jpg",
      "dur": 38.1,
      "w": 1920,
      "h": 1080
    }
  }
];
